set -g mouse on
set -g base-index 1
setw -g base-index 1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'jaclu/tmux-mullvad'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @minimal-tmux-bg "#495156"
set -g @minimal-tmux-fg "#d3c6aa"

run '~/.config/tmux/plugins/tpm/tpm'
